name: hello_wine_admin
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  questions_repository:
    path: packages/questions_repository
  authentication_repository:
    path: packages/authentication_repository
  forms_package:
    path: packages/forms_package
    
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.0
  flow_builder: ^0.0.2
  font_awesome_flutter: ^9.0.0
  formz: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/google_fonts/
    - assets/png/
  fonts:
    - family: Oleo Script
      fonts:
        - asset: assets/google_fonts/OleoScript-Bold.ttf
        - asset: assets/google_fonts/OleoScript-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/google_fonts/Roboto-Black.ttf
        - asset: assets/google_fonts/Roboto-BlackItalic.ttf
        - asset: assets/google_fonts/Roboto-Bold.ttf
        - asset: assets/google_fonts/Roboto-BoldItalic.ttf
        - asset: assets/google_fonts/Roboto-Italic.ttf
        - asset: assets/google_fonts/Roboto-Light.ttf
        - asset: assets/google_fonts/Roboto-LightItalic.ttf
        - asset: assets/google_fonts/Roboto-Medium.ttf
        - asset: assets/google_fonts/Roboto-MediumItalic.ttf
        - asset: assets/google_fonts/Roboto-Regular.ttf
        - asset: assets/google_fonts/Roboto-Thin.ttf
        - asset: assets/google_fonts/Roboto-ThinItalic.ttf
